complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
#filesize_format = "B"
filesize_metric = true
#nonzero_exit_errors = true
pivot_mode = "auto"
plugins_dir = "$HOME/.cargo/bin"
prompt = "__zoxide_hook;STARSHIP_SHELL= starship prompt"
rm_always_trash = false
skip_welcome_message = true
startup = [
	"source ~/.config/nu/zoxide.nu",
	"alias v = nvim",
	"def nuver [] {version | pivot key value}",
	"def l [path] { ls -al $path | select name type mode uid group size modified }",
	"alias la = ls -a",
	"def pm [count] { ps | sort-by mem | first $count }",
	"def pc [count] { ps | sort-by cpu | first $count }",
]
table_mode = "light"
completion_match_method = 'case-insensitive'
path = ["/home/kaka/perl5/bin", "/home/kaka/.config/nvm/versions/node/v16.1.0/bin", "/home/kaka/.gem/ruby/2.7.0/bin", "/home/kaka/.cargo/bin", "/home/kaka/.local/bin", "/usr/local/sbin", "/usr/local/bin", "/usr/bin", "/usr/bin/site_perl", "/usr/bin/vendor_perl", "/usr/bin/core_perl", "/opt/android-sdk/platform-tools", "/home/kaka/Applications", "/home/kaka/Downloads/zig/zig-linux-x86_64-0.8.0-dev.2237+8eea5eddf/"]


[env]
LC_ALL = "C"
EDITOR = "/usr/bin/nvim"
VISUAL = "/usr/bin/nvim"
LESS = "-r"
LESS_TERMCAP_mb = "\u001B[01;32m"
LESS_TERMCAP_md = "\u001B[01;32m"
LESS_TERMCAP_me = "\u001B[0m"
LESS_TERMCAP_se = "\u001B[0m"
LESS_TERMCAP_so = "\u001B[01;47;34m"
LESS_TERMCAP_ue = "\u001B[0m"
LESS_TERMCAP_us = "\u001B[01;36m"
LS_COLORS = "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
MANPAGER = "bat"
BAT_THEME = "Monokai Extended"
NVM_DIR = "/home/kaka/.config/nvm"
RUST_SRC_PATH = "/home/kaka/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/"
SHELL = "/home/kaka/.cargo/bin/nu"
_JAVA_AWT_WM_NONREPARENTING = "1"
_ZO_DATA_DIR = "/home/kaka/.cache/zoxide/"
DOTNET_CLI_TELEMETRY_OPTOUT = "1"

[line_editor]
auto_add_history = true
bell_style = "none"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "list"
edit_mode = "vi"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 10000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "Always"
snip = true
tab_width = 4
term_width = "default"
theme = "Monokai Extended"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
