#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    #enable_ale = true
    enable_neomake = false
    enable_syntastic = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"
    default_indent = 4
    filetree_direction = 'left'

# Enable autocomplete layer
#[[layers]]
#name = 'lsp'
#auto_completion_return_key_behavior = "complete"
#auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = 'format'

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "tools"

[[layers]]
  name = "git"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 30

[[custom_plugins]]
  repo = 'dracula/vim'
  name = 'dracula'

[[custom_plugins]]
  repo = 'jiangmiao/auto-pairs'

[[custom_plugins]]
  repo = 'ap/vim-css-color'

[[custom_plugins]]
  repo = 'octol/vim-cpp-enhanced-highlight'
  on_ft = ['cpp', 'c', 'h', 'cxx', 'hpp']

[[custom_plugins]]
  repo = 'vimwiki/vimwiki'

[[custom_plugins]]
  repo = 'junegunn/vim-easy-align'

[[custom_plugins]]
  repo = 'lervag/vimtex'
  on_ft = 'tex'

# [[custom_plugins]]
#   repo = 'SirVer/ultisnips'

[[custom_plugins]]
  repo = 'ziglang/zig.vim'

[[custom_plugins]]
  repo = 'mbbill/undotree'
