#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down



# set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


# # tranparency and blur
# picom &> /dev/null &
#set background
nitrogen --restore &
# notifications
dunst &
# undisplay unused mouse
unclutter &
# pulseaudio start
start-pulseaudio-x11 &
# red light for eye protection
[ $(date +"%H") -le 06 ] && [ $(date +"%H") -ge 19 ] && redshift &
# remap keys
remaps &
# turn unupdated screen off
xset dpms 600 900 1200

index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="bar$index"
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=index+1
done
