command_timeout = 100

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$docker_context\
$cmake\
$deno\
$elixir\
$elm\
$erlang\
$golang\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$python\
$ruby\
$rust\
$vagrant\
$zig\
$nix_shell\
$env_var\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$time\
$status\
$shell\
$character"""

[status]
not_executable_symbol = "🚫"
format = '[\[ $common_meaning$signal_name$maybe_int\]]($style)\n'
map_symbol = true
disabled = false

[aws]
disabled = true
